[package]
name = "tge"
version = "0.0.1"
authors = ["TakWolf <takwolf@foxmail.com>"]
edition = "2018"
description = "A lightweight cross-platform 2D game framework written in pure Rust and based on OpenGL 3.3+."
categories = ["game-engines"]
keywords = ["game", "graphics"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/TakWolf/tge"
readme = "README.md"
publish = false

[dependencies]
winit = "0.22.0"
glutin = "0.24.0"
glow = "0.4.0"
glam = "0.8.6"
image = "0.23.2"
fontdue = "0.0.4"
rodio = "0.11.0"
gilrs = "0.7.4"

[dev-dependencies]
rand = "0.7.3"
chrono = "0.4.11"
