[package]
name = "tge"
version = "0.0.4"
authors = ["TakWolf <takwolf@foxmail.com>"]
edition = "2018"
description = "A lightweight cross-platform 2D game framework written in pure Rust and based on OpenGL 3.3+."
readme = "README.md"
repository = "https://github.com/TakWolf/tge"
license = "MIT OR Apache-2.0"
keywords = ["game", "graphics"]
categories = ["game-engines"]
exclude = ["examples/**", "assets/**"]
publish = false

[dependencies]
winit = "0.26.1"
glutin = "0.28.0"
glow = "0.11.2"
glam = "0.20.2"
image = "0.24.1"
fontdue = "0.7.1"
gilrs = "0.8.2"

[dev-dependencies]
rand = "0.8.4"
chrono = "0.4.19"

[profile.dev]
opt-level = 3
