[package]
name = "tge"
version = "0.0.0"
authors = ["TakWolf <takwolf@foxmail.com>"]
edition = "2018"
description = "A lightweight 2D game framework."
categories = ["game-engines"]
keywords = ["game", "graphics"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/TakWolf/tge"
publish = false

[dependencies]
winit = "0.20.0-alpha6"
glutin = "0.22.0-alpha5"
gl = "0.14.0"
image = "0.22.3"
nalgebra = "0.19.0"
nalgebra-glm = "0.5.0"
rusttype = "0.8.2"
gilrs = "0.7.3"
rodio = "0.10.0"
