[package]
name = "tge"
version = "0.0.2"
authors = ["TakWolf <takwolf@foxmail.com>"]
edition = "2018"
description = "A lightweight cross-platform 2D game framework written in pure Rust and based on OpenGL 3.3+."
readme = "README.md"
repository = "https://github.com/TakWolf/tge"
license = "MIT OR Apache-2.0"
keywords = ["game", "graphics"]
categories = ["game-engines"]
exclude = ["examples/**", "assets/**"]
publish = false

[dependencies]
winit = "0.22.2"
glutin = "0.24.1"
glow = "0.5.0"
glam = "0.9.3"
image = "0.23.8"
ab_glyph = "0.2.5"
gilrs = "0.7.4"

[dev-dependencies]
rand = "0.7.3"
chrono = "0.4.15"

[profile.dev]
opt-level = 3
