[package]
name = "tge"
version = "0.0.0"
authors = ["TakWolf <takwolf@foxmail.com>"]
edition = "2018"
description = "TakWolf's Game Engine."
categories = ["game-engines"]
keywords = ["game", "graphics"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/TakWolf/tge"
publish = false

[dependencies]
