[package]
name = "tge"
version = "0.0.3"
authors = ["TakWolf <takwolf@foxmail.com>"]
edition = "2018"
description = "A lightweight cross-platform 2D game framework written in pure Rust and based on OpenGL 3.3+."
readme = "README.md"
repository = "https://github.com/TakWolf/tge"
license = "MIT OR Apache-2.0"
keywords = ["game", "graphics"]
categories = ["game-engines"]
exclude = ["examples/**", "assets/**"]
publish = false

[dependencies]
winit = "0.23.0"
glutin = "0.25.0"
glow = "0.6.0"
glam = "0.9.4"
image = "0.23.10"
fontdue = "0.3.2"
gilrs = "0.7.4"

[dev-dependencies]
rand = "0.7.3"
chrono = "0.4.19"

[profile.dev]
opt-level = 3
